package victor.training.java.records;

import lombok.Value;

public class RecordsIntro {
  public static void main(String[] args) {
    Point point = Point.from("1","2");
    System.out.println(point.x()); // SHOCK! no get- prefix
    // we can now see codebases that removed get- from ALL their getters
    System.out.println(point);
  }
}

// .class file contains extra bytecode generated by lombok annotation processor
//@Data // getters, setters, hashcode/equals, toString = perfect for CRUD systems
//@Value // getters, ctor, all fields=private+final, hashcode/equals, toString

record Point(int x, int y) {
  Point(String xs, String ys) {
    int xx = Integer.parseInt(xs);// java 22
    this(xx, Integer.parseInt(ys));
  }
  public static Point from(String xs, String ys) {// better than constructors on records?
    int xx = Integer.parseInt(xs);
    int yy = Integer.parseInt(ys);
    return new Point(xx, yy);
  }
}


// let's play.
