package victor.training.java.records;

import groovy.lang.Tuple3;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;
import jakarta.validation.constraints.Min;
import lombok.Value;

public class RecordsIntro {
  public static void main(String[] args) {
//    Tuple3<String, String, Integer> t3; >>>> replace with records
//    t3.getV3() = what does that integer MEAN?
    Point point = Point.from("1","2");
    System.out.println(point.x()); // SHOCK! no get- prefix
    validateAnnotations(point);

    // we can now see codebases that removed get- from ALL their getters
    System.out.println(point);
  }

  private static void validateAnnotations(Point point) {
    // apply validations on the instance
    ValidatorFactory factory = jakarta.validation.Validation.buildDefaultValidatorFactory();
    Validator validator = factory.getValidator();
    validator.validate(point).forEach(System.out::println);
  }
}
// .class file contains extra bytecode generated by lombok annotation processor
//@Data // getters, setters, hashcode/equals, toString = perfect for CRUD systems
//@Value // getters, ctor, all fields=private+final, hashcode/equals, toString

interface Displayable{
  void display();
}
class A {}


//class X extends Record {
//}


record Point(@Min(0) int x, @Min(0) int y) implements Displayable /*extends A*/{
//  private String extra; // can't hide your state

  public Point{
    if (x < 0 || y < 0) { // scary! objects refuse to instantiate if invalid
      throw new IllegalArgumentException("Negative coordinates");
    }
  }
  public Point(String xs, String ys) {
    int xx = Integer.parseInt(xs);// java 22
    this(xx, Integer.parseInt(ys));
  }
  public static Point from(String xs, String ys) {// better than constructors on records?
    int xx = Integer.parseInt(xs);
    int yy = Integer.parseInt(ys);
    return new Point(xx, yy);
  }
  public String toString() {
    return x + "," + y;
  }
  public int x() {
    return x;
  }

  @Override
  public void display() {
    System.out.println("Point at " + x + "," + y);
  }
}


//record Point3D extends Point {}

// let's play.
